blank_issues_enabled: false
contact_links:
  - name: "Reporte de vulnerabilidad de seguridad"
    url: "mailto:security@open-mexico.org"
    about: "Por favor reporta vulnerabilidades de forma privada por correo."